version: '3.8'

services:
  frontend:
    build: ./parametrization-interfaces
    ports:
      - "3000:3000"
    networks:
      - app_network

  backend-nest:
    build: ./backend/interfaz_parametrization/parametrization-app
    ports:
      - "3003:3003"
    depends_on:
      - mongodb
    networks:
      - app_network

  backend-python:
    build: ./backend/generate-files-app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

networks:
  app_network:

volumes:
  mongodb_data:
    driver: local
