version: '3.8'

services:
  frontend:
    build: ./parametrization-interfaces
    ports:
      - "3000:3000"
    networks:
      - app_network

  backend-nest:
    build: ./backend/interfaz_parametrization/parametrization-app
    ports:
      - "3003:3003"
    env_file:
      - ./backend/interfaz_parametrization/parametrization-app/.env
    depends_on:
      - mongo_container
    networks:
      - app_network
    restart: always

  backend-python:
    build: ./backend/generate-files-app
    ports:
      - "5000:5000"
    depends_on:
      - mongo_container
    networks:
      - app_network

  mongo_container:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root_user
      MONGO_INITDB_ROOT_PASSWORD: root_password
      MONGO_INITDB_DATABASE: parameter_db
    command: ["--auth"]
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

networks:
  app_network:

volumes:
  mongodb_data:
    driver: local
